# Generated by Django 4.2 on 2026-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='skill',
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(blank=True, choices=[('kampus', 'Kampus'), ('pasar', 'Pasar'), ('transportasi', 'Transportasi'), ('kerja', 'Tempat Kerja'), ('lainnya', 'Lainnya')], max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='cefr_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=5),
        ),
        migrations.AddField(
            model_name='topic',
            name='example_context',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='example_dialogue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='topic',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='topic',
            name='subtopics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
