# Generated by Django 4.2 on 2026-05-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_topic_skill_topic_category_topic_cefr_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
    ]
